#!perl

use 5.010001;
use strict;
use warnings;

use Getopt::Long;

# AUTHORITY
# DATE
# DIST
# VERSION

my %Opts = (
);

sub parse_cmdline {
    Getopt::Long::Configure("gnu_getopt", "no_ignore_case");
    my $res = GetOptions(
        'version|v'        => sub {
            print "strip-common-prefix version ", ($main::VERSION // 'dev'), "\n";
            exit 0;
        },
        'help|h'           => sub {
            print <<TEXT;
Usage:
  strip-common-prefix [OPTIONS]... [INPUT [OUTPUT]]
  strip-common-prefix --version, -v
  strip-common-prefix --help, -h
Options:

For more details, see the manpage/documentation.
TEXT
            exit 0;
        },
    );
    exit 99 if !$res;
}

sub run {
    require String::CommonPrefix;
    chomp(my @lines = <>);
    my $prefix = String::CommonPrefix::common_prefix(@lines);
    for (@lines) { s/\A\Q$prefix\E// }
    say for @lines;
}

# MAIN

parse_cmdline();
run();

1;
# ABSTRACT: Strip common prefix from each line of input
# PODNAME:

=head1 SYNOPSIS

 strip-common-prefix [OPTION]... [INPUT]

Sample input:

 foobar
 foobaz
 food

Sample output:

 bar
 baz
 d


=head1 DESCRIPTION


=head1 OPTIONS

=over

=back


=head1 EXIT CODES

0 on success.

255 on I/O error.

99 on command-line options error.


=head1 FAQ


=head1 SEE ALSO

L<strip-common-suffix>

Other utilities in L<App::CommonPrefixUtils>

=cut
